# Generated by Django 5.2 on 2025-04-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='pricing_plans',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='feature',
            field=models.ManyToManyField(related_name='features', to='events.feature'),
        ),
    ]
