# Generated by Django 5.2 on 2025-04-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_accommodation_available_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=1, upload_to='events/'),
            preserve_default=False,
        ),
    ]
