# Generated by Django 5.2 on 2025-04-18 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_accommodation_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='event',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='pricing_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.pricingplan'),
        ),
    ]
