# Generated by Django 5.2 on 2025-04-18 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_room_bed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AddOn', to='events.event'),
        ),
    ]
