# Generated by Django 5.2 on 2025-04-18 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_addon_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='available_tickets',
        ),
        migrations.CreateModel(
            name='TicketHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_of_tickets', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.pricingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.tickethold'),
        ),
        migrations.AddIndex(
            model_name='tickethold',
            index=models.Index(fields=['pricing_plan', 'expires_at'], name='events_tick_pricing_a85caa_idx'),
        ),
    ]
