# Generated by Django 5.2 on 2025-04-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_pricingplan_available_tickets_tickethold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='available_tickets',
            new_name='available_rooms',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='total_tickets',
            new_name='total_rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('single', 'Single Bed'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed')], default='double', max_length=50),
        ),
    ]
