# Generated by Django 5.2 on 2025-04-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rename_available_tickets_room_available_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available_rooms',
            field=models.PositiveIntegerField(default=0, help_text='Number of rooms currently available'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=2, help_text='Number of people the room can accommodate'),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0, help_text='Total number of rooms available'),
        ),
    ]
