# Generated by Django 5.2 on 2025-04-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_room_available_rooms_alter_room_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available_rooms',
        ),
    ]
