# Generated by Django 5.2 on 2025-04-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_addon_has_time_slots_addon_min_persons_addontimeslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='available_tickets',
        ),
        migrations.RemoveField(
            model_name='addontimeslot',
            name='available_capacity',
        ),
    ]
