# Generated by Django 5.2 on 2025-04-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_booking_user_email_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='checkin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='checkin_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='checkin_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
